from __future__ import annotations

from io import BytesIO
from typing import Dict, Iterable, Optional

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _scope_table(by_scope: Dict[str, float]) -> Table:
    rows = [["Scope", "tCO2e"]]
    for scope, value in sorted(by_scope.items()):
        rows.append([scope, f"{value:,.3f}"])

    table = Table(rows, hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#DDEAF6")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
            ]
        )
    )
    return table


def _summary_table(summary_df: pd.DataFrame, max_rows: int = 20) -> Table:
    rows = [["Category", "Activity", "Amount", "tCO2e"]]

    for _, row in summary_df.head(max_rows).iterrows():
        rows.append(
            [
                str(row.get("category", "")),
                str(row.get("activity", "")),
                f"{float(row.get('amount', 0)):,.3f}",
                f"{float(row.get('total_co2e', 0)):,.3f}",
            ]
        )

    table = Table(rows, hAlign="LEFT", colWidths=[1.2 * inch, 2.1 * inch, 1.2 * inch, 1.2 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8EFE6")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("ALIGN", (2, 1), (-1, -1), "RIGHT"),
            ]
        )
    )
    return table


def _key_value_table(data: Dict[str, object], label_a: str = "Field", label_b: str = "Value") -> Optional[Table]:
    if not data:
        return None

    rows = [[label_a, label_b]] + [[str(k), str(v)] for k, v in data.items()]
    table = Table(rows, hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F4F4F4")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ]
        )
    )
    return table


def export_pdf(
    summary: Dict[str, object],
    charts: Optional[Iterable[bytes]] = None,
    flowchart: Optional[bytes] = None,
    metadata: Optional[Dict[str, object]] = None,
    intensity_metrics: Optional[Dict[str, float]] = None,
    data_quality: Optional[Dict[str, object]] = None,
    assumptions: Optional[Iterable[str]] = None,
    change_log: Optional[Iterable[str]] = None,
) -> BytesIO:
    """Create a PDF report with metrics, charts, compliance metadata, and methodology."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, title="CarbonSuite Report")
    styles = getSampleStyleSheet()

    metadata = metadata or {}
    assumptions = list(assumptions or [])
    change_log = list(change_log or [])
    intensity_metrics = intensity_metrics or {}
    data_quality = data_quality or {}

    story = [
        Paragraph("Carbon Accounting and LCA Report", styles["Title"]),
        Spacer(1, 12),
        Paragraph("Generated by CarbonSuite", styles["Normal"]),
        Spacer(1, 18),
    ]

    metadata_table = _key_value_table(metadata)
    if metadata_table is not None:
        story.extend([Paragraph("Reporting Metadata", styles["Heading3"]), metadata_table, Spacer(1, 12)])

    total_co2e = float(summary.get("total_co2e", 0.0))
    by_scope = summary.get("by_scope", {}) or {}
    summary_df = summary.get("summary_df")

    story.extend(
        [
            Paragraph(f"Total Emissions: <b>{total_co2e:,.3f}</b> tCO2e", styles["Heading2"]),
            Spacer(1, 10),
            Paragraph("Scope Breakdown", styles["Heading3"]),
            _scope_table(by_scope),
            Spacer(1, 12),
        ]
    )

    if isinstance(summary_df, pd.DataFrame) and not summary_df.empty:
        story.extend(
            [
                Paragraph("Activity Summary", styles["Heading3"]),
                _summary_table(summary_df),
                Spacer(1, 12),
            ]
        )

    if intensity_metrics:
        intensity_table = _key_value_table(intensity_metrics, label_a="Intensity KPI", label_b="Value")
        if intensity_table is not None:
            story.extend([Paragraph("Intensity Metrics", styles["Heading3"]), intensity_table, Spacer(1, 12)])

    if data_quality:
        dq_table = _key_value_table(
            {
                "score": data_quality.get("score", ""),
                "row_count": data_quality.get("row_count", ""),
                "issues": len(data_quality.get("issue_counts", {})),
            },
            label_a="Data Quality",
            label_b="Value",
        )
        if dq_table is not None:
            story.extend([Paragraph("Data Quality", styles["Heading3"]), dq_table, Spacer(1, 12)])

    if charts:
        story.append(Paragraph("Charts", styles["Heading3"]))
        for chart_bytes in charts:
            image = Image(BytesIO(chart_bytes), width=6.2 * inch, height=3.0 * inch)
            story.extend([image, Spacer(1, 10)])

    story.append(Paragraph("Flowchart", styles["Heading3"]))
    if flowchart:
        image = Image(BytesIO(flowchart), width=6.2 * inch, height=3.4 * inch)
        story.extend([image, Spacer(1, 10)])
    else:
        story.extend([Paragraph("Flowchart image unavailable.", styles["Normal"]), Spacer(1, 10)])

    story.append(Paragraph("Methodology", styles["Heading3"]))
    story.append(
        Paragraph(
            "This report follows GHG Protocol principles using activity data multiplied "
            "by emission factors with Scope 1/2/3 aggregation.",
            styles["Normal"],
        )
    )

    if assumptions:
        story.extend([Spacer(1, 8), Paragraph("Assumptions", styles["Heading4"])])
        for item in assumptions:
            story.append(Paragraph(f"- {item}", styles["Normal"]))

    if change_log:
        story.extend([Spacer(1, 8), Paragraph("Change Log", styles["Heading4"])])
        for item in change_log:
            story.append(Paragraph(f"- {item}", styles["Normal"]))

    doc.build(story)
    buffer.seek(0)
    return buffer
